# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Chriskuei
tagline:          'Keep calm and code on'
description:      'Life style = Code + Fitness + Books'
url:              http://blog.chriskuei.com
baseurl:          http://blog.chriskuei.com

author:
  name:           'Chriskuei'
  url:            https://weibo.com/chenjiangui

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/chriskuei/chriskuei.github.io
