# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
permalink: /:year/:month/:day/:title.html
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: chriskuei
google_analytics: Chris

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 而我告别了突然

description: 被困在帝都当人工吸尘器的捂脸汪
author:
  name: 陈大鬼
  email: chenjiangui@outlook.com
  github: chriskuei
  twitter: chriskuei
  pinterest: chriskuei
  linkedin: chriskuei
  bio: Stay Hungry. Stay Foolish.
  email_md5: 27b73b1ba9a8bbb1422d01b87db3e10f

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
